name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: cmake/checkout@v1
        with:
          cmake-version: '3.22.0'

      - name: Install dependencies
        run: sudo apt-get install -y libmysqlcppconn-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Run Tests
        run: |
          cd build
          # Assuming you have tests and they are run by `make test` or similar
          make test

